# Generated by Django 4.2.5 on 2023-10-02 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_cancel', models.CharField(choices=[('Falta disponibilidad repartidor', 'Falta disponibilidad repartidor'), ('Cancelacion del usuario', 'Cancelacion del usuario'), ('Mal tiempo', 'Mal tiempo'), ('Cancelacion de la tienda', 'Cancelacion de la tienda')], max_length=50)),
                ('costo_cancel', models.IntegerField()),
                ('fecha_cancel', models.DateField()),
                ('hora_cancel', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('Tarjeta de credito', 'Tarjeta de crédito'), ('Tarjeta de debito', 'Tarjeta de débito'), ('Efectivo', 'Efectivo')], max_length=20)),
                ('monto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=40, unique=True)),
                ('precio', models.IntegerField()),
                ('categoria', models.CharField(choices=[('Alimentos y bebidas', 'Alimentos y bebidas'), ('Farmacia y cuidado personal', 'Farmacia y cuidado personal'), ('Hogar', 'Hogar')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido_repartidor', models.CharField(max_length=50, unique=True)),
                ('mail_repartidor', models.EmailField(max_length=100, unique=True)),
                ('direccion_repartidor', models.CharField(max_length=100)),
                ('fecha_nacimiento_repartidor', models.DateField()),
                ('fecha_registro_repartidor', models.DateField()),
                ('edad_repartidor', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=1)),
                ('status_repartidor', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular_tienda', models.CharField(max_length=50)),
                ('denominacion_social_tienda', models.CharField(max_length=100, unique=True)),
                ('direccion_tienda', models.CharField(max_length=30)),
                ('telefono_tienda', models.IntegerField()),
                ('zona_tienda', models.CharField(choices=[('Recoleta', 'Recoleta'), ('Caballito', 'Caballito'), ('Almagro', 'Almagro'), ('Colegiales', 'Colegiales')], max_length=10)),
                ('mail_tienda', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido_usuario', models.CharField(max_length=50, unique=True)),
                ('mail_usuario', models.EmailField(max_length=100, unique=True)),
                ('telefono_usuario', models.IntegerField()),
                ('direccion_usuario', models.CharField(max_length=50)),
                ('edad_usuario', models.IntegerField()),
                ('genero', models.CharField(max_length=1)),
                ('zona', models.CharField(max_length=50)),
                ('fecha_registro_usuario', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateField()),
                ('status_orden', models.CharField(choices=[('Entregada', 'Entregada'), ('Cancelada', 'Cancelada')], max_length=20)),
                ('hora_entrega_orden', models.TimeField()),
                ('id_cancel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.cancelacion')),
                ('id_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mi_app.pago')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.producto')),
                ('id_repartidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.repartidor')),
                ('id_tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.tienda')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.usuario')),
            ],
        ),
    ]
