# Generated by Django 4.2.5 on 2023-10-20 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mi_app', '0002_miusuariopersonalizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancelacion',
            old_name='costo_cancel',
            new_name='costo_cancelacion',
        ),
        migrations.RenameField(
            model_name='cancelacion',
            old_name='fecha_cancel',
            new_name='fecha_cancelacion',
        ),
        migrations.RenameField(
            model_name='cancelacion',
            old_name='hora_cancel',
            new_name='hora_cancelacion',
        ),
        migrations.RenameField(
            model_name='cancelacion',
            old_name='motivo_cancel',
            new_name='motivo_cancelacion',
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatars/default_avatar.png', upload_to='avatars/')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
