# Generated by Django 4.2.5 on 2023-10-20 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_rename_costo_cancel_cancelacion_costo_cancelacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='id_cancel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mi_app.cancelacion'),
        ),
    ]
