# Generated by Django 4.2.5 on 2023-10-21 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_alter_orden_id_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mi_app.miusuariopersonalizado'),
        ),
    ]
